import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Inter({
 subsets: ["latin"],
 variable: "--font-geist-sans",
});

const geistMono = JetBrains_Mono({
 subsets: ["latin"],
 variable: "--font-geist-mono",
});

export const metadata: Metadata = {
 title: "Do startup",
 description: "Generated by create next app",
 icons: {
 icon: "/favv.png", // MUST be in /public
 },
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
 <html lang="en">
 <head>
 <Script
 defer
 src="https://analytics.dostartup.in/script.js"
 data-website-id="161d48c3-1c69-42c0-9bda-125bf81249ae"
 strategy="afterInteractive"
 />
 </head>
 <body
 className={`${geistSans.variable} ${geistMono.variable} antialiased`}
 >
 {children}
 </body>
 </html>
 );
}